# Generated by Django 4.2.4 on 2023-08-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCourses',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=4)),
                ('course_number', models.IntegerField()),
                ('availability', models.CharField(max_length=10)),
                ('class_id', models.IntegerField(primary_key=True, serialize=False)),
                ('seats', models.CharField(max_length=10)),
                ('seats_avail', models.CharField(max_length=10)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
