# Generated by Django 4.2.4 on 2023-08-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_savedcourses_savedcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedcourse',
            name='course_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
