# Generated by Django 4.2.4 on 2023-08-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_savedcourse_seats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedcourse',
            name='seats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='savedcourse',
            name='seats_avail',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
