# Generated by Django 4.2.4 on 2023-08-18 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_savedcourse_seats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedcourse',
            name='term',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
